cluster:
  name: elasticsearch_medcl

thrift:
  port: 9500
  protocol: 'binary'
  frame: '10mb'


index:
  analysis:
    analyzer:

      ik:
          alias: [news_analyzer_ik,ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      mmseg:
          alias: [news_analyzer, mmseg_analyzer]
          type: org.elasticsearch.index.analysis.MMsegAnalyzerProvider

      my_analyzer:
          alias: [my_analyzer1]
          type: custom
          filter: [standard, lowercase, stop, word_delimiter]
          tokenizer: standard

      my_analyzer2:
          alias: [my_analyzer3]
          type: custom
          filter: [lowercase, stop, word_delimiter]
          tokenizer: whitespace

      my_analyzer4:
          type: custom
          filter: [standard, lowercase, stop, word_delimiter]
          tokenizer: myTokenizer1
          filter: [myTokenFilter1, myTokenFilter2]
          char_filter: [my_html]
      default:
          type: custom
          filter: [lowercase]
          tokenizer: keyword     
          
    tokenizer:
      myTokenizer1:
        type: whitespace
        max_token_length: 900
    filter:
      myTokenFilter1:
        type: stop
        #stopwords: [xxx, stop2, stop3, stop4]
      myTokenFilter2:
        type: length
        min: 0
        max: 2000
    char_filter:
      my_html:
        type: html_strip
        #escaped_tags: [xxx, yyy]  #if not explicit set will remove all tags
        read_ahead: 1024
        
index.analysis.analyzer.default.type : "mmseg"